name: rj_dart_core
description: A starting point for Dart libraries or applications.
# version: 0.1.0
# homepage: https://github.com/rj-hwang/rj_dart_core
# author: rongjihuang <rongjihuang@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
